<?php
require 'auth.php';
require 'db.php';

$record_id = isset($_GET['record_id']) ? (int)$_GET['record_id'] : 0;
if ($record_id <= 0) {
    die("Invalid record id");
}

$sql = "SELECT
            sr.record_id,
            sr.service_date,

            c.name AS customer_name,
            c.phone,
            c.address,

            v.vehicle_number,
            v.vehicle_type,
            v.brand,
            v.model,

            s.service_name,
            s.service_cost
        FROM service_records sr
        JOIN vehicles v ON sr.vehicle_id = v.vehicle_id
        JOIN customers c ON v.customer_id = c.customer_id
        JOIN services s ON sr.service_id = s.service_id
        WHERE sr.record_id = ?";

$stmt = $conn->prepare($sql);
$stmt->bind_param("i", $record_id);
$stmt->execute();
$result = $stmt->get_result();

$row = $result->fetch_assoc();
if (!$row) {
    die("Invoice not found");
}

/* Simple invoice number format */
$invoice_no = "INV-" . str_pad((string)$row['record_id'], 6, "0", STR_PAD_LEFT);
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Invoice <?php echo htmlspecialchars($invoice_no); ?></title>
<style>
    body{
        margin:0;
        font-family: Arial, Helvetica, sans-serif;
        background:#111;
        color:#fff;
        padding:30px;
    }
    .wrap{
        max-width: 820px;
        margin: 0 auto;
        background:#1c1c1c;
        border-radius:10px;
        padding:28px;
        box-shadow: 0 18px 35px rgba(0,0,0,0.6);
    }
    .top{
        display:flex;
        justify-content: space-between;
        gap: 20px;
        align-items:flex-start;
        border-bottom: 1px solid #2d2d2d;
        padding-bottom: 18px;
        margin-bottom: 18px;
    }
    .brand h1{
        margin:0;
        font-size: 22px;
        letter-spacing: 1px;
        color:#ffd700;
    }
    .brand p{
        margin:6px 0 0;
        color: rgba(255,255,255,0.75);
        font-size: 13px;
        line-height: 1.4;
    }
    .meta{
        text-align:right;
        font-size: 13px;
        color: rgba(255,255,255,0.85);
        line-height: 1.8;
    }
    .grid{
        display:grid;
        grid-template-columns: 1fr 1fr;
        gap: 16px;
        margin-top: 18px;
    }
    .card{
        background:#151515;
        border: 1px solid #2b2b2b;
        border-radius: 10px;
        padding: 14px;
    }
    .card h3{
        margin:0 0 10px;
        font-size: 14px;
        color:#ffd700;
        letter-spacing: 1px;
        text-transform: uppercase;
    }
    .card p{
        margin: 6px 0;
        font-size: 13px;
        color: rgba(255,255,255,0.85);
    }
    table{
        width:100%;
        border-collapse: collapse;
        margin-top: 18px;
        background:#151515;
        border:1px solid #2b2b2b;
        border-radius: 10px;
        overflow:hidden;
    }
    th, td{
        padding: 12px;
        border-bottom: 1px solid #2b2b2b;
        font-size: 13px;
        text-align:left;
    }
    th{
        color:#ffd700;
        text-transform: uppercase;
        letter-spacing: 1px;
        font-size: 12px;
        background:#121212;
    }
    .right{text-align:right;}
    .total-row td{
        border-bottom: none;
        font-weight: 700;
        color:#fff;
        font-size: 14px;
    }
    .actions{
        display:flex;
        gap: 10px;
        justify-content: flex-end;
        margin-top: 18px;
    }
    .btn{
        padding: 10px 14px;
        border-radius: 8px;
        border: none;
        cursor:pointer;
        font-weight: 700;
        letter-spacing: 0.5px;
    }
    .btn-print{ background:#ffd700; }
    .btn-back{ background:#333; color:#fff; text-decoration:none; display:inline-block; }

    /* Print styling */
    @media print {
        body{ background:#fff; color:#000; padding:0; }
        .wrap{ box-shadow:none; background:#fff; color:#000; border-radius:0; }
        .card, table{ background:#fff; border:1px solid #ddd; }
        th{ background:#f5f5f5; color:#000; }
        .brand h1{ color:#000; }
        .actions{ display:none; }
    }
</style>
</head>
<body>

<div class="wrap">
    <div class="top">
        <div class="brand">
            <h1>Benny's Original Motor Service</h1>
            <p>
                Vehicle Service Invoice<br>
                Generated by Vehicle Service DB System
            </p>
        </div>
        <div class="meta">
            <div><b>Invoice:</b> <?php echo htmlspecialchars($invoice_no); ?></div>
            <div><b>Date:</b> <?php echo htmlspecialchars($row['service_date']); ?></div>
        </div>
    </div>

    <div class="grid">
        <div class="card">
            <h3>Customer</h3>
            <p><b>Name:</b> <?php echo htmlspecialchars($row['customer_name']); ?></p>
            <p><b>Phone:</b> <?php echo htmlspecialchars($row['phone']); ?></p>
            <p><b>Address:</b> <?php echo htmlspecialchars($row['address']); ?></p>
        </div>

        <div class="card">
            <h3>Vehicle</h3>
            <p><b>Number:</b> <?php echo htmlspecialchars($row['vehicle_number']); ?></p>
            <p><b>Type:</b> <?php echo htmlspecialchars($row['vehicle_type']); ?></p>
            <p><b>Brand/Model:</b> <?php echo htmlspecialchars($row['brand']." ".$row['model']); ?></p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Service</th>
                <th class="right">Cost</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?php echo htmlspecialchars($row['service_name']); ?></td>
                <td class="right">₹ <?php echo number_format((float)$row['service_cost'], 2); ?></td>
            </tr>
            <tr class="total-row">
                <td class="right"><b>Total</b></td>
                <td class="right">₹ <?php echo number_format((float)$row['service_cost'], 2); ?></td>
            </tr>
        </tbody>
    </table>

    <div class="actions">
        <a class="btn btn-back" href="view_records.php">⬅ Back</a>
        <button class="btn btn-print" onclick="window.print()">🧾 Print Invoice</button>
    </div>
</div>

</body>
</html>